os: osx
osx_image: xcode7.3
compiler: clang

# language: cpp

# compiler:
#   - gcc

# before_install:
#   # upgrade g++ and libstdc++ to build nghttp2
#   - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
#   - sudo apt-add-repository --yes ppa:smspillaz/cmake-2.8.12
#   - sudo apt-get --yes update
#   - sudo apt-get install --yes cmake cmake-data g++-4.8 libstdc++-4.8-dev php5-cgi wget
#   - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi
#   - $CXX --version
#   # for speed, pre-install deps installed in `before_script` section as ubuntu packages
#   - sudo apt-get install -qq cpanminus libipc-signal-perl liblist-moreutils-perl libwww-perl libio-socket-ssl-perl zlib1g-dev

# before_script:
#   # install nghttp2 with `--enable-app` (optionally required for running HTTP/2 tests)
#   - sudo apt-get install -qq libev-dev
#   - curl -L https://github.com/tatsuhiro-t/nghttp2/releases/download/v1.4.0/nghttp2-1.4.0.tar.gz | tar xzf -
#   - (cd nghttp2-1.4.0 && ./configure --prefix=/usr --disable-threads --enable-app && make && sudo make install)
#   - curl -L https://curl.haxx.se/download/curl-7.50.0.tar.gz | tar xzf -
#   - (cd curl-7.50.0 && ./configure --prefix=/usr --with-nghttp2 --disable-shared && make && sudo make install)

# install:
#   - sudo apt-get install dnsutils
before_script:
  - "set -e"

script:
  # - curl --version
  # - nslookup 127.0.0.1.xip.io
  # - sudo find /usr/lib/libz* | xargs otool -L
  # - brew update
  # - brew install --quiet openssl
  # - sudo find /usr/ -name "*libssl*" | xargs otool -L
  - find /usr/lib/ -name "libz*" | otool -L
  - |
    export INSTALL_DIR=${HOME}/local
    mkdir ${INSTALL_DIR}
    SPDYLAY_VERSION=1.3.2
    curl -L https://github.com/tatsuhiro-t/spdylay/releases/download/v${SPDYLAY_VERSION}/spdylay-${SPDYLAY_VERSION}.tar.gz | tar xzf -
    (cd spdylay-${SPDYLAY_VERSION} && ./configure --prefix=${INSTALL_DIR} --disable-shared && make && make install)

addons:
  hosts:
    - 127.0.0.1.xip.io
    - alternate.127.0.0.1.xip.io
